#params from adaprive clustering 
/clustering_node:
  ros__parameters:
    input_topic: /lidar_points #/lidar_points #"/patchworkpp/nonground"
    frame_id: "hesai_lidar"

    #clustering
    minClusterSize : 1        # Minimum cluster size to filter out noise
    maxClusterSize : 500        # Maximum size for large objects
    voxelX: 0.8               #// Down-sampling resolution in X (meters)
    voxelY: 0.8                  #// Down-sampling resolution in Y (meters)
    voxelZ: 1.0                #// Down-sampling resolution in Z (meters)
    countThreshold: 10          #  // Minimum points per voxel

    #filter for clusters
    clusterMaxX: 100.4
    clusterMaxY: 100.4
    clusterMaxZ: 100.4
    clusterMinX: -0.1
    clusterMinY: -0.1
    clusterMinZ: -0.1
    maxHeight: 1.0          #of the lowest point

    #filter on Z
    downFilterLimits: -0.5
    upFilterLimits: 0.5

    #segmentation
    distanceThreshold: 0.1
    maxIterations: 500
    probability: 0.95
    optimizeCoefficients: false

    #options
    filterOnZ: true
    segment: true
    publishFilteredPc: true
    publishSegmentedPc: true 
    
    

